### ISSUE TITLE
Sign up Feature

### ISSUE THREAD

**Issue by noumandev11** [CoalAI/boilerplate-django#13]

**Comment by aishatasaduq** [comment]
@MKRNaqeebi we are using authemail package in boilerplate. It provides us with api/accounts/signup endpoint which signups user and also sends email for email verification. It is mentioned in readme. Do we need to customize its behavior or we need to create our own api?
We are also using password reset functionality from this package and it also has change password functionality.

**Comment by aishatasaduq** [comment]
I have added url of signup in urls.py file

**Comment by noumandev11** [comment]
completed
