### ISSUE TITLE
Add Verify Email Functionality in boiler plate

### ISSUE THREAD

**Issue by noumandev11** [CoalAI/boilerplate-django#5]

**Comment by aishatasaduq** [comment]
Dev story:
- Add verify email functionality using 'Django-Verify-Email'
- [link](https://pypi.org/project/Django-Verify-Email/) of documentation

**Comment by aishatasaduq** [comment]
Update:
- package i was using earlier was MVT based so I couldn't use it with our rest frame work
- using django-rest-authemail 2.1.4 now
- [link](https://pypi.org/project/django-rest-authemail/) of documentation

**Comment by aishatasaduq** [comment]
This task took longer than expected due to a blocker.
blocker: print environment variables in template
